DROP DATABASE IF EXISTS xingyun;

CREATE DATABASE IF NOT EXISTS xingyun default charset utf8 COLLATE utf8_bin;

GRANT ALL PRIVILEGES ON *.* TO 'xingyun'@'localhost' IDENTIFIED BY 'xingyun' WITH GRANT OPTION;

CREATE TABLE task (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  pid INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '父id',
  title VARCHAR(255) NOT NULL COMMENT '标题',
  content TEXT COMMENT '内容',
  end_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '截止时间',
  c_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  m_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP COMMENT '修改时间',
  c_user INT(11) NOT NULL COMMENT '创建人',
  owner INT(11) NOT NULL COMMENT '归属人',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '状态:0-初始,1-进行 2-完成',
  PRIMARY KEY (id)
) ENGINE InnoDB DEFAULT CHARSET=utf8 COMMENT '任务表';


CREATE TABLE task_comment (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  pid INT(11) NOT NULL COMMENT '父id',
  task_id INT(11) NOT NULL COMMENT '任务id',
  content TEXT NOT NULL COMMENT '内容',
  PRIMARY KEY (id)
) ENGINE InnoDB DEFAULT CHARSET=utf8 COMMENT '任务描述表';


CREATE TABLE user (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  user_id VARCHAR(255) NOT NULL COMMENT '用户id',
  nick_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '昵称',
  mobile VARCHAR(15) NOT NULL COMMENT '手机号',
  email VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'email',
  salt VARCHAR(31) NOT NULL COMMENT 'salt',
  password VARCHAR(63) NOT NULL COMMENT '密码',
  head_img_url VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像url',
  c_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  m_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP COMMENT '修改时间',
  last_login_time TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最新登陆时间',
  PRIMARY KEY (id),
  UNIQUE KEY `uk_user_id` (`user_id`)
) ENGINE InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';







